In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [3]:
# data load
df = pd.read_csv('Data_Polis.csv')

print("Five upper row")
display(df.head()) 

print("\ndata info")
print(df.info())

df2 = pd.read_csv('Data_Klaim.csv')

print("\nFive upper row")
display(df2.head())

print("\ndata info")
print(df2.info())

Five upper row

  Nomor Polis Plan Code Gender  Tanggal Lahir  Tanggal Efektif Polis Domisili
0    POL-0001     M-003      M       19640811               20140603  JAKARTA
1    POL-0002     M-003      M       19710730               20140603  JAKARTA
2    POL-0003     M-001      M       19790821               20160808  JAKARTA
3    POL-0004     M-003      M       20140724               20160811  JAKARTA
4    POL-0005     M-001      F       19810114               20150828  JAKARTA

data info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nomor Polis            4096 non-null   object
 1   Plan Code              4096 non-null   object
 2   Gender                 4096 non-null   object
 3   Tanggal Lahir          4096 non-null   int64
 4   Tanggal Efektif Polis  4096 non-null   int64
 5   Domisili               4096 non-null   object
dtypes: int64(2), object(4)
memory usage: 192.1+ KB
None

Five upper row

,Claim ID,Nomor Polis,Reimburse/Cashless,Inpatient/Outpatient,ICD Diagnosis,ICD Description,Status Klaim,Tanggal Pembayaran Klaim,Tanggal Pasien Masuk RS,Tanggal Pasien Keluar RS,Nominal Klaim Yang Disetujui,Nominal Biaya RS Yang Terjadi,Lokasi RS
0,C-0001-M,POL-0176,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,2024-07-08,2024-05-27,2024-05-27,28093653.0,6.143948e+06,Singapore
1,C-0002-M,POL-3288,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-08-06,2024-07-15,2024-07-15,80987278.0,8.230952e+07,Malaysia
2,C-0003-M,POL-1786,R,OP,C18.9,"MALIGNANT NEOPLASM, COLON, UNSPECIFIED",PAID,2024-10-17,2024-05-16,2024-05-16,183047130.0,1.928599e+08,Singapore
3,C-0004-M,POL-1786,R,OP,C34,MALIGNANT NEOPLASM OF BRONCHUS AND LUNG,PAID,2024-09-03,2024-07-18,2024-07-18,191424386.0,1.914244e+08,Singapore
4,C-0005-M,POL-2778,R,OP,C50,MALIGNANT NEOPLASM OF BREAST,PAID,NaN,2024-06-06,2024-06-06,138936357.0,1.389364e+08,Singapore

data info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4627 entries, 0 to 4626
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Claim ID                       4627 non-null   object
 1   Nomor Polis                    4627 non-null   object
 2   Reimburse/Cashless             4627 non-null   object
 3   Inpatient/Outpatient           4590 non-null   object
 4   ICD Diagnosis                  4621 non-null   object
 5   ICD Description                4621 non-null   object
 6   Status Klaim                   4627 non-null   object
 7   Tanggal Pembayaran Klaim       4590 non-null   object
 8   Tanggal Pasien Masuk RS        4627 non-null   object
 9   Tanggal Pasien Keluar RS       4627 non-null   object
 10  Nominal Klaim Yang Disetujui   4627 non-null   float64
 11  Nominal Biaya RS Yang Terjadi  4627 non-null   float64
 12  Lokasi RS                      4620 non-null   object
dtypes: float64(2), object(11)
memory usage: 470.1+ KB
None

In [ ]:
df2 = pd.read_csv('Data_Klaim.csv')

print("\nFive upper row")
display(df2.head())

print("\ndata info")
print(df2.info())